server:
  port: 8077

spring:
  application:
    name: socket
  datasource:
    url: jdbc:mysql://13.124.200.73:3306/insaeng?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: gospelee
    password: 1234qwer
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000
      # Session wait_timeout 수정
      connection-init-sql: set wait_timeout = 600
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      repositories:
        enabled: false

redis:
  host: localhost
  port: 6379

kakao:
  issuer: https://kauth.kakao.com
  app-key: 9878afc0afde051ed656f416f67c4492
