server:
  port: 8008
  servlet:
    context-path: /api

spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://13.124.200.73:3306/gospelee?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: gospelee
    password: 1234qwer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
    redis:
      cache-null-values:true
  data:
    redis:
      repositories:
        enabled: false

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

redis:
  host: localhost
  port: 6377

kakao:
  issuer: https://kauth.kakao.com
  app-key: bc9ac0fd4cd17a858c971f6d4aede305

firebase:
  admin-sdk:
    path: firebase/oog-dev-firebase-adminsdk-9zrmg-6208291886.json
