server:
  port: 8008
  servlet:
    context-path: /api

spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/gospelee?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: gospelee
    password: 1234qwer
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000
      # Session wait_timeout 수정
      connection-init-sql: set wait_timeout = 600
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
    redis:
      cache-null-values:true
  data:
    redis:
      repositories:
        enabled: false

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

redis:
  host: localhost
  port: 6377

kakao:
  issuer: https://kauth.kakao.com
  app-key: bc9ac0fd4cd17a858c971f6d4aede305

firebase:
  admin-sdk:
    path: firebase/oog-dev-firebase-adminsdk-9zrmg-6208291886.json

auth:
  max-age: 60 * 60 * 24 # 1일
  cookie:
    path: /
    domains:
      localhost,
      13.124.200.73,
      127.0.0.1
