server:
  port: 8008
  domain: https://api.oog.kr:8888
  servlet:
    context-path: /api

cors:
  allowed-origins:
    - https://admin.oog.kr:8800

spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/gospelee?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: gospelee
    password: 1234qwer
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000
      # Session wait_timeout 수정
      connection-init-sql: set wait_timeout = 600
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cache:
    type: redis
    redis:
      cache-null-values:true
  data:
    redis:
      repositories:
        enabled: false

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

redis:
  embedded: true
  host: redis
  port: 6379

auth:
  super-id: admin
  super-pass: admin
  exclude-paths:
    - /bible/view/*
    - /account/qr/enter
    - /account/qr/check
    - /file/*
    - /app-link/*
    - /article
    - /announcement/unauthorized/BRAND_STORY
  allow-pending-paths:
    - /api/account/qr/req/*

file:
  base-path: /Users/ej/dev/testFiles/gospelee/api
