name: Build and Deploy to GHCR

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up QEMU (multi-arch support)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push API image
        run: |
          docker buildx build --no-cache \
            --platform linux/amd64 \
            -f dockerfile.api \
            -t ghcr.io/${{ github.repository }}/gospelee-api:latest \
            --label build_time=$(date +%s) \
            --push .

      - name: Build and Push Admin image
        run: |
          docker buildx build --no-cache \
            --platform linux/amd64 \
            -f dockerfile.admin \
            -t ghcr.io/${{ github.repository }}/gospelee-admin:latest \
            --label build_time=$(date +%s) \
            --push .

      - name: Build and Push Landing image
        run: |
          docker buildx build --no-cache \
            --platform linux/amd64 \
            -f dockerfile.landing \
            -t ghcr.io/${{ github.repository }}/gospelee-landing:latest \
            --label build_time=$(date +%s) \
            --push .
