name: Build and Deploy to GHCR

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -f dockerfile.api -t ghcr.io/${{ github.repository }}/gospelee-api:latest .

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}/gospelee-api:latest
