name: Build and Deploy to GHCR

on:
  push:
    branches: [ deploy ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push API image
        run: |
          docker buildx build --no-cache \
            --platform linux/amd64 \
            -f dockerfile.api \
            -t ghcr.io/${{ github.repository }}/gospelee-api:latest \
            --label build_time=$(date +%s) \
            --push .

  build-admin:
    runs-on: ubuntu-latest
    needs: build-api
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Admin image
        run: |
          docker buildx build --no-cache \
            --platform linux/amd64 \
            -f dockerfile.admin \
            -t ghcr.io/${{ github.repository }}/gospelee-admin:latest \
            --label build_time=$(date +%s) \
            --push .

  build-landing:
    runs-on: ubuntu-latest
    needs: build-admin
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Landing image
        run: |
          docker buildx build --no-cache \
            --platform linux/amd64 \
            -f dockerfile.landing \
            -t ghcr.io/${{ github.repository }}/gospelee-landing:latest \
            --label build_time=$(date +%s) \
            --push .
